---
title: "Cleaning"
output: html_notebook
---

```{r}
library(spotifyr)
library(tidyverse)
library(infer)
library(lubridate)
```

```{r}
Sys.setenv(SPOTIFY_CLIENT_ID = '38edc55f660e4f5689cff0abf8d275a5')
Sys.setenv(SPOTIFY_CLIENT_SECRET = '5f29ddcdbddd414bbe9557088f974a53')

access_token <- get_spotify_access_token()
```

```{r}
spotify_data <- read_csv("raw_data/spotify_data.csv")
diff_spotify_combine_select <- read_csv("raw_data/diff_spotify_combine.csv")
```


Clean the main, full dataset
```{r}
spotify_data_clean <- spotify_data %>% 
  select(artists, name, id, popularity, release_date, year, explicit,
         duration_ms, key, mode, tempo, everything()) %>% 
  rename("track_name" = "name",
         "duration_sec" = "duration_ms") %>% 
  mutate(artists = str_remove_all(artists, "[\\['\\]]+"),
         acousticness = acousticness * 100,
         danceability = danceability * 100,
         energy = energy * 100,
         instrumentalness = instrumentalness * 100,
         liveness = liveness * 100,
         speechiness = speechiness * 100,
         valence = valence * 100,
         loudness = (loudness + 60) * 100 / 65,
         duration_sec = duration_sec / 1000,
         no_of_artists = 1 + str_count(artists, ","),
         is_popular = if_else(popularity >= 50, TRUE, FALSE)) %>% 
  filter(year >= 1960 &
          year < 2020) %>% 
  mutate(decade = case_when(
    year >= 1950 & year < 1960 ~ 1950,
    year >= 1960 & year < 1970 ~ 1960,
    year >= 1970 & year < 1980 ~ 1970,
    year >= 1980 & year < 1990 ~ 1980,
    year >= 1990 & year < 2000 ~ 1990,
    year >= 2000 & year < 2010 ~ 2000,
    year >= 2010 & year < 2020 ~ 2010,
    year >= 2020 ~ 2020,
    TRUE ~ FALSE
  )) %>% 
  mutate(explicit = as.factor(explicit),
         key = as.factor(key),
         mode = as.factor(mode))
```


Pivot the data for easier analysis
```{r}
spotify_data_clean_pivot <- spotify_data_clean %>% 
  pivot_longer(cols = acousticness:valence,
              names_to = "audio_feature",
              values_to = "value") %>% 
  group_by(year, audio_feature) %>% 
  mutate(avg_feature = mean(value))
```

Join with the other spotify dataset to retrieve extra info
```{r}
spotify_data_clean_join <- spotify_data_clean %>% 
  left_join(diff_spotify_combine_select, by = c("id" = "track_id")) %>%
  mutate(genres = na_if(genres, "[]")) %>% 
  mutate(genres = str_remove_all(genres, "[\\['\\]]+")) %>% 
  mutate(genres = if_else(str_detect(genres, "[f][o][l][k]"), "folk", genres),
         genres = if_else(str_detect(genres, "[r][a][p]"), "rap", genres),
         genres = if_else(str_detect(genres, "[i][n][d][i][e]"), "indie", genres),
         genres = if_else(str_detect(genres, "[s][o][u][l]"), "soul", genres),
         genres = if_else(str_detect(genres, "[d][i][s][c][o]"), "disco", genres),
         genres = if_else(str_detect(genres, "[c][l][a][s][s][i][c][a][l]"), "classical", genres),
         genres = if_else(str_detect(genres, "[c][o][u][n][t][r][y]"), "country", genres),
         genres = if_else(str_detect(genres, "[j][a][z][z]"), "jazz", genres),
         genres = if_else(str_detect(genres, "[b][l][u][e][s]"), "blues", genres),
         genres = if_else(str_detect(genres, "[m][e][t][a][l]"), "metal", genres),
         genres = if_else(str_detect(genres, "[p][u][n][k]"), "punk", genres),
        #genres = if_else(str_detect(genres, "[r][o][c][k][-][a][n][d][-][r][o][l][l]"), "rock&roll", genres),
         genres = if_else(str_detect(genres, "[r][o][c][k]"), "rock", genres),
         genres = if_else(str_detect(genres, "[r][e][g][g][a][e][t][o][n]"), "reggaeton", genres),
         genres = if_else(str_detect(genres, "[r][e][g][g][a][e]"), "reggae", genres),
         genres = if_else(str_detect(genres, "[h][i][p] [h][o][p]"), "hip hop", genres),
         genres = if_else(str_detect(genres, "[r][&][b]"), "r&b", genres),
         genres = if_else(str_detect(genres, "[p][o][p]"), "pop", genres),
         genres = if_else(str_detect(genres, "[d][a][n][c][e]"), "dance", genres),
         genres = if_else(str_detect(genres, "[h][o][u][s][e]"), "house", genres),
         genres = if_else(str_detect(genres, "[m][e][x][i][c][a][n]"), "mexican", genres)) %>% 
  mutate(#year = ymd(paste0(year, "-01-01")),
         #decade = ymd(paste0(decade, "-01-01")),
         time_signature = as.factor(time_signature)) %>% 
  select(-release_date)

write_csv(spotify_data_clean_join, "clean_data/spotify_clean_join.csv")
```


