---
title: "R Notebook"
output: html_notebook
---

```{r}
library(spotifyr)
library(janitor)
library(tidyverse)
library(purrr)
library(ggfortify)
library(GGally)
library(lubridate)
library(pracma)
library(modelr)
library(pROC)
library(broom)
```


```{r include=FALSE}
spotify_data_clean_join <- read_csv("clean_data/spotify_clean_join.csv")
spotify_data <- read_csv("raw_data/spotify_data.csv")
spotify_genres_modelling <- read_csv("clean_data/spotify_genres_modelling.csv")
```

```{r}
n_data <- nrow(spotify_data_for_modelling)

test_index <- sample(1:n_data, size = n_data*0.2)

train_log_mod <- slice(spotify_data_for_modelling, -test_index)
test_log_mod <- slice(spotify_data_for_modelling, test_index)

options(scipen = 999)

```


```{r}
model_1_loud <- glm(is_popular ~ loudness,
             family = "binomial",
             data = train_log_mod)

summary(model_1_loud)

train_model_1_loud <- train_log_mod %>%
  add_predictions(model_1_year, type = "response")

roc_obj_mod1 <- train_model_1_loud %>%
  roc(response = is_popular, predictor = pred)

roc_curve <- ggroc(
  data = list(
    mod1 = roc_obj_mod1
  ), 
  legacy.axes = TRUE) +
  coord_fixed()

auc(roc_obj_mod1)
```


```{r}
model_2_energy <- glm(is_popular ~ loudness + explicit,
             family = "binomial",
             data = train_log_mod)

summary(model_2_energy)

tidy(model_2_energy)

train_model_2_energy <- train_log_mod %>%
  add_predictions(model_2_energy, type = "response")

roc_obj_mod2 <- train_model_2_energy %>%
  roc(response = is_popular, predictor = pred)

roc_curve <- ggroc(
  data = list(
    mod2 = roc_obj_mod2
  ), 
  legacy.axes = TRUE) +
  coord_fixed()

auc(roc_obj_mod2)
```

```{r}
model_3_explicit <- glm(is_popular ~ loudness + explicit + danceability,
             family = "binomial",
             data = train_log_mod)

summary(model_3_explicit)

tidy(model_3_explicit)

train_model_3_explicit <- train_log_mod %>%
  add_predictions(model_3_explicit, type = "response")

roc_obj_mod3 <- train_model_3_explicit %>%
  roc(response = is_popular, predictor = pred)

roc_curve <- ggroc(
  data = list(
    mod3 = roc_obj_mod3
  ), 
  legacy.axes = TRUE) +
  coord_fixed()

auc(roc_obj_mod3)
```


Final Logistic Regression Model
```{r}
model_4_final <- glm(is_popular ~ loudness + explicit + danceability + no_of_artists,
             family = "binomial",
             data = train_log_mod)

summary(model_4_final)

tidy(model_4_final)

train_model_4_final <- train_log_mod %>%
  add_predictions(model_4_final, type = "response")

roc_obj_mod4 <- train_model_4_final %>%
  roc(response = is_popular, predictor = pred)

threshold <- 0.5
train_model_4_final <- train_model_4_final %>%
  mutate(pred_thresh_0.6 = pred >= threshold)

conf_table <- train_model_4_final %>%
  tabyl(is_popular, pred_thresh_0.6)
conf_table

roc_curve <- ggroc(
  data = list(
    best_model = roc_obj_mod4
  ), 
  legacy.axes = TRUE) +
  coord_fixed()

auc(roc_obj_mod4)
```


```{r}
(63259 + 6777) / 95920
```



Test how the final model performs over different decades

```{r}
log_mod_1960 <- train_log_mod %>% 
  filter(decade == 1960 |
           decade == 1970 |
           decade == 1980)

model_60_70_80 <- glm(is_popular ~ loudness + explicit + danceability + no_of_artists,
             family = "binomial",
             data = log_mod_1960)

summary(model_60_70_80)

tidy(model_60_70_80)

train_model_60_70_80 <- log_mod_1960 %>%
  add_predictions(model_60_70_80, type = "response")

roc_obj_mod_60_70_80 <- train_model_60_70_80 %>%
  roc(response = is_popular, predictor = pred)

roc_curve <- ggroc(
  data = list(
    best_model = roc_obj_mod4,
    mod_60_70_80 = roc_obj_mod_60_70_80
  ), 
  legacy.axes = TRUE) +
  coord_fixed()

auc(roc_obj_mod_60_70_80)
```
```{r}
log_mod_1990 <- train_log_mod %>% 
  filter(decade == 1990 |
           decade == 2000 |
           decade == 2010)

model_90_00_10 <- glm(is_popular ~ loudness + explicit + danceability + no_of_artists,
             family = "binomial",
             data = log_mod_1990)

summary(model_90_00_10)

tidy(model_90_00_10)

train_model_90_00_10 <- log_mod_1990 %>%
  add_predictions(model_90_00_10, type = "response")

roc_obj_mod_90_00_10 <- train_model_90_00_10 %>%
  roc(response = is_popular, predictor = pred)


roc_curve <- ggroc(
  data = list(
    best_model = roc_obj_mod4,
    dec_60s_70s_80s = roc_obj_mod_60_70_80,
    dec_90s_00s_10s = roc_obj_mod_90_00_10
  ), 
  legacy.axes = TRUE) +
  coord_fixed()

auc(roc_obj_mod_90_00_10)
```

```{r}
21549 + 1728 / 
```


Model with top 20 genres included
```{r}
model_genres <- glm(is_popular ~ loudness + explicit + danceability + no_of_artists + energy + top_genres,
              family = "binomial",
              data = spotify_genres_modelling)

 summary(model_genres)
 tidy(model_genres)
 
 train_model_genres <- spotify_genres_modelling %>%
   add_predictions(model_genres, type = "response")

 roc_obj_mod_genre <- train_model_genres %>%
   roc(response = is_popular, predictor = pred)

 roc_curve <- ggroc(
   data = list(
     mod4 = roc_obj_mod4,
     model_genres = roc_obj_mod_genre
   ),
   legacy.axes = TRUE) +
   coord_fixed()

 auc(roc_obj_mod_genre)
```

