---
title: "What Makes a Song Popular on Spotify"
output: html_notebook
---

### Context

#### Business Intelligence and Data-Driven Decision Making

- Working with Universal Music Group, I have been asked to investigate what makes a song popular on Spotify. This will help inform the business for future releases, giving them extra insight in to what gives a song a high popularity score on Spotify.

- Universal Music Group (UMG) are one of the largest music company/record labels in the world. They operate a large, diverse portfolio of record labels and publishing companies, who represent some of the biggest names in the music industry. Their primary business activities involve discovering, developing, promoting and distributing music. 

- My analysis will give UMG a good indication of what new music could be popular on Spotify as well as providing information that they can hand down to subsidiary labels, artists and producers for creating new music with a goal to being popular on Spotify.

### Data

#### Internal and External Data Sources

- For this project I used a combination of 3 externally sourced datasets. These were all taken from Kaggle. All of these were created using the Spotify Web API. The main dataset originally contained 169,000 rows with each row providing information about 1 song. Each row originially had 19 columns with information about each track.

- When the datasets were joined and cleaned ready for analysis, there were 121,656 rows with 22 columns. There were less rows as I removed everything before 1960, this was due to inconsistencies and lack of information. There were a few more columns as we gained `genre` and `number of followers` from the join, as well as a couple of columns I created.

#### Type of Data

- The majority of data I worked with was continuous numerical data. This included all of the `audio features` which I put on a scale of 0 - 100, including decimals.
- There were some discrete numerical columns only containing whole numbers. These included the `key`, which was on a scale of 0 - 11 and the `number of followers` an artist has.
- I also had a lot of nominal categorical data to work with. These came in the form of the `track_name`, `artists` or `genre`.
- I also had a few date variables, such as `date_of_release`, `year` and `decade`.

#### Data Formats

- All of the data came in the form of CSV files from Kaggle. 

#### Data Quality & Bias

- The orginal dataset I was working from contained no missing values. It was complete and I had no reason to believe any of it was incorrect as it was taken from the Spotify Web API. When I joined the datasets together I created a lot of NA values as there was no information on `genre` or `number of followers` for almost half of the data. 

- In terms of bias there was a small issue where the songs I was was working with were already "popular" songs. For many years after the year 2000 there were very few songs with a popularity score under 50. I think if I would have slightly different findings if I used a dataset with a broader range of `popularity` score.

### Ethics

#### Ethical Issues in Data Sourcing and Extraction

- I don't have any major concerns over the sourcing or extraction of the data. However, it was a dataset put together by someone else and made available to download on Kaggle, which means I can't say for certain that the data is 100% accurate. Although I have no reason to believe it is not accurate.

#### Ethical Implications of Business Requirements

- There are no ethical implications of the business requirements. The data is all from the Spotify Web API which is publicly available with a Spotify for Developers login.

### Analysis

#### Stages in the Data Analysis Process

__Exploratory Analysis__

- Audio Features change over time. I looked at how each of the `audio_features` changed from 1960 - 2020. I also conducted hypothesis tests to check that the difference in means were significant from 1960 - 2020, which they were.

- The proportion of explicit songs from 1960 - 2020. I had 2000 tracks/rows for each year in my final, clean dataset. I calculated the proportion of explicit tracks each year and plotted that from 1960 - 2020. 

- The mean popularity change over time. I took the mean popularity score from each year and plotted that over time. This was to see how heavily weighted the Spotify algorithm used to calculate the popularity score was towards recent music.

__Linear Regression__

- To help me answer my question of what makes a song "popular" on spotify, I decided to build an explanatory linear regression model. This type of analysis is used to determine the strength of the relationship between a response variable and multiple explanatory variables.

- In this stage I look for correlations between `popularity` and the rest of my variables. I then add the 'most significant' variable to the model. I repeated this until my model stopped improving.

__Logistic Regression__

- I created a variable called is_popular which gave me a TRUE if the songs popularity score was 50 or greater, and FALSE otherwise. I used this binary outcome to create a logistic regression model to help explain if a song `is_popular`.

#### Tools for Data Analysis

I used RStudio for all of my data analysis. Within RStudio I used these packages...

- `tidyverse` - integrated set of tools for working with data in R
- `janitor` - used for data cleaning and preperation
- `lubridate` - provides a set of functions to work with dates and times
- `spotifyr` - for working with the Spotify Web API
- `infer` - used for hypothesis testing
- `modelr` - makes it easier to work on statistical models
- `ggfortify` - enhancing visualisations of ggplot2
- `GGally` - set of tools for creating and comparing multiple plots
- `mosaic` - used for model comparison (ANOVA test)
- `pROC` - for visualisation of roc curves during logistic regression

#### Descriptive, Diagnostic, Predictive and Prescriptive Analysis

- My analysis falls under __Diagnostic Analytics__ as it helps us understand why songs have been given a certain popularity score. I used model building to find correlations, to help explain what gives a song a high popularity score on Spotify. 


